name: SE-Dev

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
      - BACKEND_URL=http://backend:5000
    develop:
      watch:
        - action: sync          # sync files without rebuilding
          path: ./frontend/src
          target: /app/src
        - action: rebuild       # rebuild image when these change
          path: ./frontend/package.json
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/config/config.env
    develop:
      watch:
        - action: sync          # sync files without rebuilding
          path: ./backend
          target: /app
          ignore: "**/node_modules/**"
        - action: rebuild       # rebuild image when these change
          path: ./backend/package.json